---
exclude-paths:
  - node_modules
  - dist
  - build
  - vendor
  - .venv
  - venv
exclude-patterns:
  - ^(.*/)?.*\.min\.(js|css)$
  - ^(.*/)?.*(test|spec)\.(py|js|ts)$
engines:
  eslint:
    enabled: false
  pmd:
    enabled: false
  pmd-legacy:
    enabled: false
  remark-lint:
    enabled: true
  metrics:
    enabled: true
