exclude-paths:
  - '**/*.min.js'
  - '**/*.min.css'
  - node_modules
  - dist
  - build

engines:
  exclude-paths:
    - '**/*.min.*'
  eslint:
    enabled: false
  pmd:
    enabled: false
  pmd-legacy:
    enabled: false
